const Discord = require('discord.js');
const http = require('axios');
const { isBuffer } = require('util');


module.exports = {
    name: "genkey",
    category: "utility",
    description: "Generates An Oxygen U Key",
    usage: ";genkey",
    permission: "SEND_MESSAGES",
    run: async (client, message, args) => {
       
if(message.member.roles.cache.find(r => r.name === "OxyPremium")){
 
  http.get('https://oxygenu.xyz/KeySystem/GenKey.php?WRUIGUORDUOGHIOUER9GOIFREOIUHGOIUREOIUOU9HG9ORUEHGO9UHOU=1')
    .then(response => {
    let bbig = response.data.toString();
    const EmbedYes = new Discord.MessageEmbed()
    .setColor('RANDOM')
    .setTimestamp()
    .setTitle(`Oxygen U | Gen Key`)
    .setDescription('This Key Should Last About 6 Hours, Please Do Not Spam Use This Command.')
    .addField('Rules:', 'Do Not Give Users Your Key Or You Will Be Demoted! DO NOT SHARE YOUR KEY!')
    .addField('Key', `\`${bbig}\``)
    .setFooter(`Command Run By ${message.author.username}`,message.author.avatarURL())
    message.delete();
   message.author.send(EmbedYes);

   let log = new Discord.MessageEmbed()
   .setTitle("Oxygen U Key Generated")
   .addField('Generated By:' , `${message.author.username} with and ID: ${message.author.id}`)
   .addField('Generated Time:', message.createdAt)
   .addField("Key:", bbig)
   .addField("Guild:", `Guild Name ${message.guild.name} with an ID: ${message.guild.id}`)
   .setFooter('Oxydoggo')
   client.channels.cache.find(channel => channel.name === "logs").send(log);
    })
    .catch(error => {
      console.log(error);
    });

  

  }
  else{
   message.author.send('You Do Not Have Permission To Run This Command :x:');
   message.delete(); 
  }
 }     
}