const Discord = require('discord.js');
const http = require('axios');
const { isBuffer } = require('util');
const talkedRecently = new Set();
const command = require('../../handlers/command');

module.exports = {
    name: "genkey",
    category: "utility",
    description: "Generates An Oxygen U Key",
    usage: ";genkey",
    permission: "SEND_MESSAGES",
    run: async (client, message, args) => {
       
if(message.member.roles.cache.find(r => r.name === "OxyPremium") || message.member.permissions.has("VIEW_AUDIT_LOG")){
 if(!message.member.permissions.has("ADMINISTRATOR")) {
  if (talkedRecently.has(message.author.id)) {
   return message.author.send("You Already Used This Command Please Wait Before Trying to  Use This Again!❌").then(msg =>{
     msg.delete({timeout : 5000})
   })
} 
else 
{
  http.get('https://oxygenu.xyz/KeySystem/GenKey.php?WRUIGUORDUOGHIOUER9GOIFREOIUHGOIUREOIUOU9HG9ORUEHGO9UHOU=1')
  .then(response => {
  let bbig = response.data.toString();
  const EmbedYes = new Discord.MessageEmbed()
  .setColor('RANDOM')
  .setTimestamp()
  .setTitle(`Oxygen U | Gen Key`)
  .setDescription('This Key Should Last About 6 Hours, Please Do Not Spam Use This Command.')
  .addField('Rules:', 'Do Not Give Users Your Key Or You Will Be Demoted! DO NOT SHARE YOUR KEY!')
  .addField('Key', `\`${bbig}\``)
  .setFooter(`Command Run By ${message.author.username}`,message.author.avatarURL())
  message.author.send(EmbedYes);
  message.delete();
 let log = new Discord.MessageEmbed()
 .setTitle("Oxygen U Key Generated")
 .addField('Generated By:' , `${message.author.username} with and ID: ${message.author.id}`)
 .addField('Generated Time:', message.createdAt)
 .addField("Key:", `\`${bbig}\``)
 .addField("Guild:", `Guild Name: ${message.guild.name.toString()} with an ID: ${message.guild.id.toString()}`)
 .setFooter('Oxydoggo')
 client.channels.cache.find(channel => channel.name === "logs").send(log);
 

  })
  .catch(error => {
    console.log(error);
  });

 talkedRecently.add(message.author.id);
 setTimeout(() => {
   talkedRecently.delete(message.author.id);
 }, 21600000);
}
 }
 else{
  http.get('https://oxygenu.xyz/KeySystem/GenKey.php?WRUIGUORDUOGHIOUER9GOIFREOIUHGOIUREOIUOU9HG9ORUEHGO9UHOU=1')
  .then(response => {
  let bbig = response.data.toString();
  const EmbedYes = new Discord.MessageEmbed()
  .setColor('RANDOM')
  .setTimestamp()
  .setTitle(`Oxygen U | Gen Key`)
  .setDescription('This Key Should Last About 6 Hours, Please Do Not Spam Use This Command.')
  .addField('Rules:', 'Do Not Give Users Your Key Or You Will Be Demoted! DO NOT SHARE YOUR KEY!')
  .addField('Key', `\`${bbig}\``)
  .setFooter(`Command Run By ${message.author.username}`,message.author.avatarURL())
 message.author.send(EmbedYes);
 message.delete();
 let log = new Discord.MessageEmbed()
 .setTitle("Oxygen U Key Generated")
 .addField('Generated By:' , `${message.author.username} with and ID: ${message.author.id}`)
 .addField('Generated Time:', message.createdAt)
 .addField("Key:", `\`${bbig}\``)
 .addField("Guild:", `Guild Name: ${message.guild.name} with an ID: ${message.guild.id}`)
 .setFooter('Oxydoggo')
 client.channels.cache.find(channel => channel.name === "logs").send(log);
 

  })
  .catch(error => {
    console.log(error);
  });
 }
}
else{
  let noPermEmbed = new Discord.MessageEmbed()
            .setTitle("Oxygen U")
            .setDescription(":x:Missing Permissions!" + ` You Need ${command.permission.toString()} to use this command!`)
            .setColor("#00000")
            .setFooter(`Command Run By ${message.author.username}`,message.author.avatarURL())
             message.author.reply(noPermEmbed).then(msg =>{
                msg.delete({timeout: 7000})
                message.delete({timeout: 7000})
             });
}
 }
}